#!/bin/bash

# Usage: ./client <hostname> <portnum> [file_path]
# all parameters are optional
# example usage: 
#       ./client 127.0.0.1 8080 Dostoyevsky.txt
#       ./client 127.0.0.1 8080 <Dostoyevsky.txt
#       ./client 127.0.0.1 8080

HOST=${1:-"127.0.0.1"}
PORT=${2:-8080}
FILE=${3:-""}

if [ -z "$FILE" ]; then
  python3 client.py "$HOST" "$PORT"
else
  python3 client.py "$HOST" "$PORT" "$FILE"
fi